/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedItemsRouteImport } from './routes/_authenticated/items'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDevCountersRouteImport } from './routes/_authenticated/dev/counters'
import { Route as AuthenticatedDevPlaygroundRouteImport } from './routes/_authenticated/dev/playground'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedItemsRoute = AuthenticatedItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDevCountersRoute =
  AuthenticatedDevCountersRouteImport.update({
    id: '/dev/counters',
    path: '/dev/counters',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDevPlaygroundRoute =
  AuthenticatedDevPlaygroundRouteImport.update({
    id: '/dev/playground',
    path: '/dev/playground',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/items': typeof AuthenticatedItemsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/dev/counters': typeof AuthenticatedDevCountersRoute
  '/dev/playground': typeof AuthenticatedDevPlaygroundRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/items': typeof AuthenticatedItemsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/dev/counters': typeof AuthenticatedDevCountersRoute
  '/dev/playground': typeof AuthenticatedDevPlaygroundRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/items': typeof AuthenticatedItemsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/dev/counters': typeof AuthenticatedDevCountersRoute
  '/_authenticated/dev/playground': typeof AuthenticatedDevPlaygroundRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/items'
    | '/profile'
    | '/dev/counters'
    | '/dev/playground'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/items'
    | '/profile'
    | '/dev/counters'
    | '/dev/playground'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/items'
    | '/_authenticated/profile'
    | '/_authenticated/dev/counters'
    | '/_authenticated/dev/playground'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/items': {
      id: '/_authenticated/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof AuthenticatedItemsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dev/counters': {
      id: '/_authenticated/dev/counters'
      path: '/dev/counters'
      fullPath: '/dev/counters'
      preLoaderRoute: typeof AuthenticatedDevCountersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dev/playground': {
      id: '/_authenticated/dev/playground'
      path: '/dev/playground'
      fullPath: '/dev/playground'
      preLoaderRoute: typeof AuthenticatedDevPlaygroundRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedItemsRoute: typeof AuthenticatedItemsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedDevCountersRoute: typeof AuthenticatedDevCountersRoute
  AuthenticatedDevPlaygroundRoute: typeof AuthenticatedDevPlaygroundRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedItemsRoute: AuthenticatedItemsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedDevCountersRoute: AuthenticatedDevCountersRoute,
  AuthenticatedDevPlaygroundRoute: AuthenticatedDevPlaygroundRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
